apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-variant-autoscaler-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: workload-variant-autoscaler
imagePullSecrets:
  - name: {{ .Values.wva.imagePullSecret | default "" }}
