apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: workload-variant-autoscaler
    control-plane: controller-manager
  name: workload-variant-autoscaler-controller-manager-metrics-monitor
  namespace: {{ .Values.wva.prometheus.monitoringNamespace }}
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 10s
    path: /metrics
    port: https
    scheme: https
    tlsConfig:
      insecureSkipVerify: {{ .Values.wva.prometheus.tls.insecureSkipVerify }}
      {{- if and .Values.wva.prometheus.caCert (not .Values.wva.prometheus.tls.insecureSkipVerify) }}
      caFile: /etc/ssl/certs/prometheus-ca.crt
      {{- end }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: workload-variant-autoscaler
      control-plane: controller-manager