apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: workload-variant-autoscaler
  name: workload-variant-autoscaler-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workload-variant-autoscaler-leader-election-role
subjects:
- kind: ServiceAccount
  name: workload-variant-autoscaler-controller-manager
  namespace: {{ .Release.Namespace }}
