prometheus:
  prometheusSpec:
    web:
      tlsConfig:
        keySecret:
          name: prometheus-tls
          key: tls.key
        cert:
          secret:
            name: prometheus-tls
            key: tls.crt
    externalUrl: "https://kube-prometheus-stack-prometheus.workload-variant-autoscaler-monitoring.svc.cluster.local:9090"
    enableFeatures:
      - remote-write-receiver
    resources:
      requests:
        memory: 400Mi
        cpu: 100m
      limits:
        memory: 800Mi
        cpu: 200m 