{{- if .Values.guidellm.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: guidellm-job-1
  namespace: {{ .Values.llmd.namespace }}
spec:
  template:
    spec:
      containers:
        - name: guidellm
          image: {{ .Values.guidellm.image }}
          args:
            - benchmark
            - --target=http://infra-inference-scheduling-inference-gateway:80
            - --rate-type=constant
            - --rate={{ .Values.guidellm.rate | quote }}
            - --max-seconds={{ .Values.guidellm.maxSeconds | quote }}
            - --model={{ .Values.variantAutoscaling.modelID | quote }}
      restartPolicy: Never
  backoffLimit: 4
{{- end }}

