apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-ca
  namespace: {{ .Values.wva.prometheus.monitoringNamespace }}
data:
  ca.crt: |
    {{- if .Values.wva.prometheus.caCert }}
{{ .Values.wva.prometheus.caCert | indent 4 }}
    {{- else }}
    # CA certificate not provided - using system CA bundle
    {{- end }}
